# Generated by Django 5.1.1 on 2024-10-27 19:47

import apps.products.models.validators
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('inn', models.CharField(max_length=12, validators=[apps.products.models.validators.validate_inn], verbose_name='INN')),
                ('bik', models.CharField(max_length=9, validators=[apps.products.models.validators.validate_bik], verbose_name='BIK')),
                ('phone_number', models.CharField(max_length=20, validators=[apps.products.models.validators.validate_russian_phone_number], verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
