# Generated by Django 5.1.1 on 2024-11-09 12:11

import apps.products.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[apps.products.models.validators.validate_bik], verbose_name='BIK'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[apps.products.models.validators.validate_inn], verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.products.models.validators.validate_russian_phone_number], verbose_name='Phone number'),
        ),
    ]
