# Generated by Django 5.1.1 on 2024-12-07 21:34

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('creating_type', models.CharField(choices=[('Manual', 'Manual'), ('Async task', 'Async task')], max_length=20, verbose_name='Creating type')),
                ('drive_url', models.CharField(help_text="A url with backup's folder on Google drive", max_length=120, verbose_name='Drive url')),
                ('folder_id', models.CharField(help_text="An id of backup's folder on Google drive", max_length=120, verbose_name='Folder id')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Done', 'Done')], default='Pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
            },
        ),
    ]
