# Generated by Django 5.1.1 on 2024-10-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='invoices.invoice', verbose_name='Invoice id'),
            preserve_default=False,
        ),
    ]
