# Generated by Django 5.1.1 on 2024-10-29 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicepayment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.DecimalValidator(7, 2), django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)], verbose_name='Amount'),
        ),
    ]
