# Generated by Django 5.1.1 on 2024-10-30 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_amount_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(10000000)], verbose_name='Amount'),
        ),
    ]
