# Generated by Django 5.1.1 on 2024-10-30 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_amount_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 11, 13, 15, 6, 18, 458086), verbose_name='Deadline'),
        ),
    ]
