# Generated by Django 5.1.1 on 2024-10-30 12:06

import apps.invoices.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deadline',
            field=models.DateField(default=apps.invoices.models.utils.generate_two_week_pass_date, verbose_name='Deadline'),
        ),
    ]
