# Generated by Django 5.1.1 on 2024-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not paid', 'Not paid')], default='Not paid', max_length=10, verbose_name='Payment status'),
        ),
    ]
