# Generated by Django 5.1.1 on 2024-11-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_expired',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is expired'),
        ),
    ]
