# Generated by Django 5.1.1 on 2024-10-30 12:06

import apps.users.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
    ]
